### ISSUE TITLE
OpenCV not being initialised

### ISSUE THREAD

**Issue by ghost** [Rohithkvsp/Form-N-Fun#2]
I installed the APK and downloaded the OpenCV manager, but when I try to run it, all I get is this error:
```
OpenCV was not initialised correctly. Application will be shut down.
```
How do I fix this? I'm using a rooted Samsung Galaxy S7 Edge on stock ROM.

**Comment by Rohithkvsp** [comment]
Follow this [link](https://github.com/opencv/opencv/issues/7235), I hope the issue will be solved.
