### ISSUE TITLE
Error:(81) Android NDK: Application targets deprecated ABI(s): armeabi mips mips64    

### ISSUE THREAD

**Issue by maxwellnewage** [Rohithkvsp/Form-N-Fun#4]
I have this error when I try to compile the project, in this part of code:

`
_deprecated_abis := $(filter $(NDK_DEPRECATED_ABIS),$(NDK_APP_ABI))
ifneq ($(_deprecated_abis),)
    $(call __ndk_warning,Application targets deprecated ABI(s): $(_deprecated_abis))
    $(call __ndk_warning,Support for these ABIs will be removed in a future NDK release.)
endif
`

**Comment by Rohithkvsp** [comment]
what is the NDK version, you are using ?

**Comment by maxwellnewage** [comment]
i forgot install OpenCV3.
My NDK version is the lastest, version 16

**Comment by Rohithkvsp** [comment]
Is it resolved or still showing the same error ?

**Comment by maxwellnewage** [comment]
resolved! Thanks!
