### ISSUE TITLE
look like sensor cant roll the ball

### ISSUE THREAD

**Issue by s33ju** [Rohithkvsp/Form-N-Fun#5]
i have tried in 4 mobile but unable to make it work,

**Comment by Rohithkvsp** [comment]
Did u try Apk in repo, or build your own ? if you build, check the **azimuth, pitch, roll values** in the **logs**. If they are 0.0 then there might be problem with magnetometer or accelerometer.  

I think few Android phones don't have magnetometer, I am not sure what are they, Also please check your mobile specifications.

**Comment by Rohithkvsp** [comment]
Hi Muhammad Sajeel, have you checked  logs, mobile specifications?

**Comment by s33ju** [comment]
yes it could be that my all phones dont have magnetometer,
and i tried apk from your repo and also by building it from android studio changing amb values as you mentioned in ReadME, 
BTW thanks for heads up.
and again it is amazing experiment bro, keep it up

**Comment by Rohithkvsp** [comment]
Hi Muhammad Sajeel, Thank you
