### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Rudloff** [Rohithkvsp/Form-N-Fun#6]
Hello,

Would you be interested in publishing this app on [F-Droid](https://f-droid.org/)?

**Comment by Rohithkvsp** [comment]
Hi ,

Yes

**Comment by Rudloff** [comment]
Great! I really like the idea of your game and it would be nice to have it in the repository.

I opened a request for package here so we can discuss how to package it: https://gitlab.com/fdroid/rfp/issues/608

However, I see your repository does not have a [license](https://choosealicense.com/). We require apps to be published under a free license.

**Comment by Rohithkvsp** [comment]
Hi ,
I added the license..

**Comment by Rudloff** [comment]
Thanks! I will try to work on packaging the app this week-end.

**Comment by Rudloff** [comment]
One last thing, would it be possible to add a [tagged release](https://github.com/Rohithkvsp/Form-N-Fun/releases)?
It makes packaging a lot easier.

**Comment by Rohithkvsp** [comment]
Hi, 
sorry for the late response, I added tagged releases.

**Comment by Rudloff** [comment]
Thank you!

**Comment by IzzySoft** [comment]
@Rohithkvsp there's another issue keeping us from building your app: an error in CV3 which was fixed in CV4 – but your app wants CV3 (where the error still exists, see [here](https://gitlab.com/fdroid/rfp/issues/608#note_81975317)). Any chance you could migrate up to CV4?

**Comment by Rohithkvsp** [comment]
@IzzySoft, I will look into it & try to build it with cv4 this weekend.

**Comment by IzzySoft** [comment]
@Rohithkvsp just a heads-up: which weekend will that be? 😉

**Comment by Rohithkvsp** [comment]
LOL :-D, I am sorry. I was busy with some other work, Later I forget. I will soon work on this.

**Comment by IzzySoft** [comment]
Ah, soon™ :rofl:

**Comment by Rohithkvsp** [comment]
Added CV4 support

**Comment by IzzySoft** [comment]
Thanks! – Could you give it another try then, @Rudloff?

**Comment by Rudloff** [comment]
I managed to build the app: https://gitlab.com/fdroid/fdroiddata/merge_requests/4854

@Rohithkvsp Would it be possible to tag a new release that includes OpenCV 4 support?

**Comment by Rohithkvsp** [comment]
I did

**Comment by paulvi** [comment]
Could you please share name in F-droid or link?

**Comment by IzzySoft** [comment]
The website is slow to update and doesn't have it yet, but you can see it via my repo browser: [Form-N-Fun](https://apt.izzysoft.de/fdroid/index/apk/com.formfun?repo=main). Of course the F-Droid client on your Android device should find it as well if you have an up-to-date index, @paulvi.

**Comment by paulvi** [comment]
There is also alternative G-droid client, which does not rely on index updates.  
But it actually fails to find.

OK, Hooray 🎆 🎆  Form-N-Funn is finally available.  
When searching with F-droid client, type at least "form-", as only "form" will not reveal it.

**Comment by IzzySoft** [comment]
@paulvi all F-Droid clients rely on index updates. If they have no up-to-date index (on-device or server-side), they cannot reflect latest updates.
